name: Fast Forward to Release
on:
  check_suite:
    types:
    - completed
  pull_request_review:
    types:
    - submitted
jobs:
  merge:
    if: ${{ (github.event.action == 'completed' && github.event.check_suite.head_branch || github.event.pull_request.head.ref) == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
    - id: poll_status
      if: ${{ github.event.action == 'submitted' && github.event.review.state == 'approved' }}
      env:
        PR_REF=${{ github.event.pull_request.head.ref }}
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/commits/${PR_REF}/status \
        -o "${{ runner.temp }}/status.json"
        status=$(jq '.state=="success"' < "${{ runner.temp }}/status.json")
        echo "MERGE=${status}" >> "${GITHUB_ENV}"

    - id: poll_reviews
      if: ${{ github.event.action == 'completed' && github.event.check_suite.conclusion == 'success' }}
      env:
        PR_REF=${{ github.event.check_suite.pull_requests[0].number }}
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${PR_REF}/reviews \
        -o "${{ runner.temp }}/reviews.json"
        check=$(jq '[map(.state=="APPROVED")|all,(length>=2)]|all' < "${{ runner.temp }}/reviews.json")
        echo "MERGE=${check}" >> "${GITHUB_ENV}"

    - name: Checkout code into workspace directory
      if: ${{ env.MERGE == 'true' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ssh-key: ${{ inputs.SSH_PRIVATE_KEY }}
        persist-credentials: true

    - name: Set Git references
      if: ${{ env.MERGE == 'true' }}
      run: |
        jq_expr='.pull_requests[]|select("${{ github.event.check_suite.head_branch }}"==.head.ref)|"BASE_REF=\(.base.ref)\nHEAD_REF=\(.head.ref)"'
        jq -r "${jq_expr}" <<HERE >> "${GITHUB_ENV}"
        ${{ toJSON(github.event.check_suite) }}
        HERE

    - name: Fast Forward Merge
      if: ${{ env.MERGE == 'true' }}
      run: |
        if [ -n "${BASE_REF}" ]; then
          git checkout "${BASE_REF}"
          git merge --ff-only "${HEAD_REF}"
          git push origin "${BASE_REF}"
        fi
