name: Fast Forward to Release
on:
  check_suite:
    types:
    - completed
  pull_request:
    types:
    - edited
  pull_request_review:
    types:
    - submitted
jobs:
  merge:
    if: ${{ (github.event.action != 'completed' && github.event.pull_request.head.ref || github.event.check_suite.head_branch) == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - id: current_labels
      run: |
        echo "REVIEWED=${{ github.event.action == 'submitted' && contains(github.event.pull_request.labels,':detective:') }}" >> "${GITHUB_ENV}"
        echo "CHECKED=${{ github.event.action == 'submitted' && contains(github.event.pull_request.labels,':gear:') }}" >> "${GITHUB_ENV}"

    - id: add_reviewed_label
      if: ${{ github.event.action == 'submitted' && github.event.review.state == 'approved' }}
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/labels" \
          -d '{"labels":[":detective:"]}'
        echo "REVIEWED=true" >> "${GITHUB_ENV}"

    - id: remove_reviewed_label
      if: ${{ github.event.action == 'submitted' && github.event.review.state != 'approved' || github.event.action == 'edited' }}
      run: |
        curl -L -X DELETE -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/labels/%3Adetective%3A"
        echo "REVIEWED=false" >> "${GITHUB_ENV}"

    - id: add_checked_label
      if: ${{ github.event.action == 'completed' && github.event.check_suite.conclusion == 'success' }}
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.check_suite.pull_requests[0].number }}/labels" \
          -d '{"labels":[":gear:"]}'
        echo "CHECKED=true" >> "${GITHUB_ENV}"

    - id: remove_checked_label
      if: ${{ github.event.action == 'completed' && github.event.check_suite.conclusion != 'success' || github.event.action == 'edited' }}
      env:
        PR: ${{ github.event.action == 'completed' && github.event.check_suite.pull_requests[0].number || github.event.pull_request.number }}
      run: |
        curl -L -X DELETE -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${{ env.PR }}/labels/%3Agear%3A"
        echo "CHECKED=false" >> "${GITHUB_ENV}"

    - id: query_reviewed_label
      if: ${{ env.CHECKED == 'true' && env.REVIEWED == 'false' }}
      run: |
        echo "CHECKED=$(curl -L -X GET -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${{ env.PR }}/labels" \
        | jq -r '(.[]|select(.name=="bug")|any)')" >> "${GITHUB_ENV}"

    - name: Checkout code into workspace directory
      if: ${{ env.CHECKED == 'true' && env.REVIEWED == 'true' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ssh-key: ${{ inputs.SSH_PRIVATE_KEY }}
        persist-credentials: true

    - name: Set Git references
      if: ${{ env.CHECKED == 'true' && env.REVIEWED == 'true' }}
      run: |
        jq_expr='.pull_requests[]|select("${{ github.event.check_suite.head_branch }}"==.head.ref)|"BASE_REF=\(.base.ref)\nHEAD_REF=\(.head.ref)"'
        jq -r "${jq_expr}" <<HERE >> "${GITHUB_ENV}"
        ${{ toJSON(github.event.check_suite) }}
        HERE

    - name: Fast Forward Merge
      if: ${{ env.CHECKED == 'true' && env.REVIEWED == 'true' }}
      run: |
        if [ -n "${BASE_REF}" ]; then
          git checkout "${BASE_REF}"
          git merge --ff-only "${HEAD_REF}"
          git push origin "${BASE_REF}"
        fi
